# Generated by Django 2.2.2 on 2019-06-24 12:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('country', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Directors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('released', models.DateField(default=datetime.datetime.now)),
                ('runtime', models.IntegerField()),
                ('description', models.TextField(max_length=300)),
                ('genre', models.CharField(choices=[('ROMANCE', 'Romance'), ('COMEDY', 'Comedy'), ('THRILLER', 'Thriller'), ('SCI-FI', 'Sci-Fi'), ('HORROR', 'Horror'), ('ADVENTURE', 'Adventure'), ('MYSTERY', 'Mystery')], default='COMEDY', max_length=15)),
                ('language', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Directors')),
                ('main_actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Actors')),
            ],
        ),
        migrations.AddField(
            model_name='directors',
            name='movies_directed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movies'),
        ),
        migrations.AddField(
            model_name='actors',
            name='movies_featured',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movies'),
        ),
    ]
